POST http://localhost:3001/api/numbers/ HTTP/1.1
content-type: application/json

{
    "name": "sas",
    "number": "53234343433"
}

###

DELETE http://localhost:3001/api/numbers/ HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/info/ HTTP/1.1


###
GET http://localhost:3001/api/numbers/ HTTP/1.1